-- 样例数据：pipeline_history（100 条）
-- 用于端到端验证，可重复执行（先清空全表再插入）
-- 修改规则见 prompts/12_modify_data_examples_prompt.md

DELETE FROM `pipeline_history`;

INSERT INTO `pipeline_history`
  (`start_time`, `subtask`, `module`, `case_name`, `case_result`, `log_url`, `screenshot_url`, `pipeline_url`, `reports_url`, `case_level`, `main_module`, `owner`, `platform`, `code_branch`, `analyzed`)
VALUES
  ('202601201730', 'subtask-01', 'auth,user',        'test_login_success',         'passed', 'www.sohu.com', 'www.sina.com', 'www.tencent.com', 'www.baidu.com', 'l0', 'auth',    '张三', 'win',  'master',    0),
  ('202601211000', 'subtask-02', 'auth',       'test_login_invalid_pwd',     'passed', 'www.sohu.com', 'www.sina.com', 'www.tencent.com', 'www.baidu.com', 'l1', 'auth',    '张三', 'mac',  '930bugfix', 0),
  ('202601221500', 'subtask-03', 'payment',     'test_pay_alipay',            'failed', 'www.sohu.com', 'www.sina.com', 'www.tencent.com', 'www.baidu.com', 'l2', 'payment', '李四', 'ohos', 'master',    1),
  ('202601231200', 'subtask-04', 'order,payment',        'test_create_order',          'passed', 'www.sohu.com', 'www.sina.com', 'www.tencent.com', 'www.baidu.com', 'l3', 'order',   '王五', 'win',  '930bugfix', 0),
  ('202601241800', 'subtask-05', 'order,cart',      'test_cancel_order',          'failed', 'www.sohu.com', 'www.sina.com', 'www.tencent.com', 'www.baidu.com', 'l0', 'order',   '王五', 'mac',  'master',    0),
  ('202601251000', 'subtask-06', 'cart,order,product',     'test_add_to_cart',           'passed', 'www.sohu.com', 'www.sina.com', 'www.tencent.com', 'www.baidu.com', 'l1', 'cart',    '赵六', 'ohos', '930bugfix', 0),
  ('202601261400', 'subtask-01', 'search',        'test_search_keyword',        'passed', 'www.sohu.com', 'www.sina.com', 'www.tencent.com', 'www.baidu.com', 'l2', 'search',  '张三', 'win',  'master',    0),
  ('202601271600', 'subtask-02', 'search',     'test_search_empty',          'passed', 'www.sohu.com', 'www.sina.com', 'www.tencent.com', 'www.baidu.com', 'l3', 'search',  '张三', 'mac',  '930bugfix', 0),
  ('202601281800', 'subtask-03', 'profile,auth',   'test_update_avatar',         'failed', 'www.sohu.com', 'www.sina.com', 'www.tencent.com', 'www.baidu.com', 'l0', 'profile', '李四', 'ohos', 'master',    1),
  ('202601201730', 'subtask-04', 'profile,user','test_change_nickname',       'passed', 'www.sohu.com', 'www.sina.com', 'www.tencent.com', 'www.baidu.com', 'l1', 'profile', '李四', 'win',  '930bugfix', 0),
  ('202601211000', 'subtask-05', 'auth,user',        'test_login_success',         'passed', 'www.sohu.com', 'www.sina.com', 'www.tencent.com', 'www.baidu.com', 'l2', 'auth',    '张三', 'mac',  'master',    0),
  ('202601221500', 'subtask-06', 'auth',       'test_login_invalid_pwd',     'passed', 'www.sohu.com', 'www.sina.com', 'www.tencent.com', 'www.baidu.com', 'l3', 'auth',    '张三', 'ohos', '930bugfix', 0),
  ('202601231200', 'subtask-01', 'payment',     'test_pay_alipay',            'passed', 'www.sohu.com', 'www.sina.com', 'www.tencent.com', 'www.baidu.com', 'l0', 'payment', '李四', 'win',  'master',    0),
  ('202601241800', 'subtask-02', 'order,payment',        'test_create_order',          'passed', 'www.sohu.com', 'www.sina.com', 'www.tencent.com', 'www.baidu.com', 'l1', 'order',   '王五', 'mac',  '930bugfix', 0),
  ('202601251000', 'subtask-03', 'order,cart',      'test_cancel_order',          'passed', 'www.sohu.com', 'www.sina.com', 'www.tencent.com', 'www.baidu.com', 'l2', 'order',   '王五', 'ohos', 'master',    0),
  ('202601261400', 'subtask-04', 'cart,order',     'test_add_to_cart',           'failed', 'www.sohu.com', 'www.sina.com', 'www.tencent.com', 'www.baidu.com', 'l3', 'cart',    '赵六', 'win',  '930bugfix', 0),
  ('202601271600', 'subtask-05', 'search',        'test_search_keyword',        'passed', 'www.sohu.com', 'www.sina.com', 'www.tencent.com', 'www.baidu.com', 'l0', 'search',  '张三', 'mac',  'master',    0),
  ('202601281800', 'subtask-06', 'search',     'test_search_empty',          'failed', 'www.sohu.com', 'www.sina.com', 'www.tencent.com', 'www.baidu.com', 'l1', 'search',  '张三', 'ohos', '930bugfix', 0),
  ('202601201730', 'subtask-01', 'profile,auth',   'test_update_avatar',         'passed', 'www.sohu.com', 'www.sina.com', 'www.tencent.com', 'www.baidu.com', 'l2', 'profile', '李四', 'win',  'master',    0),
  ('202601211000', 'subtask-02', 'profile,user,auth','test_change_nickname',       'passed', 'www.sohu.com', 'www.sina.com', 'www.tencent.com', 'www.baidu.com', 'l3', 'profile', '李四', 'mac',  '930bugfix', 0),
  ('202601221500', 'subtask-03', 'auth,user',        'test_login_success',         'failed', 'www.sohu.com', 'www.sina.com', 'www.tencent.com', 'www.baidu.com', 'l0', 'auth',    '张三', 'ohos', 'master',    0),
  ('202601231200', 'subtask-04', 'auth',       'test_login_invalid_pwd',     'passed', 'www.sohu.com', 'www.sina.com', 'www.tencent.com', 'www.baidu.com', 'l1', 'auth',    '张三', 'win',  '930bugfix', 0),
  ('202601241800', 'subtask-05', 'payment',     'test_pay_alipay',            'passed', 'www.sohu.com', 'www.sina.com', 'www.tencent.com', 'www.baidu.com', 'l2', 'payment', '李四', 'mac',  'master',    0),
  ('202601251000', 'subtask-06', 'order,payment',        'test_create_order',          'passed', 'www.sohu.com', 'www.sina.com', 'www.tencent.com', 'www.baidu.com', 'l3', 'order',   '王五', 'ohos', '930bugfix', 0),
  ('202601261400', 'subtask-01', 'order,cart',      'test_cancel_order',          'failed', 'www.sohu.com', 'www.sina.com', 'www.tencent.com', 'www.baidu.com', 'l0', 'order',   '王五', 'win',  'master',    0),
  ('202601271600', 'subtask-02', 'cart,order',     'test_add_to_cart',           'passed', 'www.sohu.com', 'www.sina.com', 'www.tencent.com', 'www.baidu.com', 'l1', 'cart',    '赵六', 'mac',  '930bugfix', 0),
  ('202601281800', 'subtask-03', 'search',        'test_search_keyword',        'passed', 'www.sohu.com', 'www.sina.com', 'www.tencent.com', 'www.baidu.com', 'l2', 'search',  '张三', 'ohos', 'master',    0),
  ('202601201730', 'subtask-04', 'search',     'test_search_empty',          'passed', 'www.sohu.com', 'www.sina.com', 'www.tencent.com', 'www.baidu.com', 'l3', 'search',  '张三', 'win',  '930bugfix', 0),
  ('202601211000', 'subtask-05', 'profile,auth',   'test_update_avatar',         'failed', 'www.sohu.com', 'www.sina.com', 'www.tencent.com', 'www.baidu.com', 'l0', 'profile', '李四', 'mac',  'master',    1),
  ('202601221500', 'subtask-06', 'profile,user','test_change_nickname',       'passed', 'www.sohu.com', 'www.sina.com', 'www.tencent.com', 'www.baidu.com', 'l1', 'profile', '李四', 'ohos', '930bugfix', 0),
  ('202601231200', 'subtask-01', 'auth,user',        'test_login_success',         'passed', 'www.sohu.com', 'www.sina.com', 'www.tencent.com', 'www.baidu.com', 'l2', 'auth',    '张三', 'win',  'master',    0),
  ('202601241800', 'subtask-02', 'auth',       'test_login_invalid_pwd',     'passed', 'www.sohu.com', 'www.sina.com', 'www.tencent.com', 'www.baidu.com', 'l3', 'auth',    '张三', 'mac',  '930bugfix', 0),
  ('202601251000', 'subtask-03', 'payment',     'test_pay_alipay',            'failed', 'www.sohu.com', 'www.sina.com', 'www.tencent.com', 'www.baidu.com', 'l0', 'payment', '李四', 'ohos', 'master',    0),
  ('202601261400', 'subtask-04', 'order,payment,cart',        'test_create_order',          'passed', 'www.sohu.com', 'www.sina.com', 'www.tencent.com', 'www.baidu.com', 'l1', 'order',   '王五', 'win',  '930bugfix', 0),
  ('202601271600', 'subtask-05', 'order,cart',      'test_cancel_order',          'passed', 'www.sohu.com', 'www.sina.com', 'www.tencent.com', 'www.baidu.com', 'l2', 'order',   '王五', 'mac',  'master',    0),
  ('202601281800', 'subtask-06', 'cart,order',     'test_add_to_cart',           'passed', 'www.sohu.com', 'www.sina.com', 'www.tencent.com', 'www.baidu.com', 'l3', 'cart',    '赵六', 'ohos', '930bugfix', 0),
  ('202601201730', 'subtask-01', 'search',        'test_search_keyword',        'failed', 'www.sohu.com', 'www.sina.com', 'www.tencent.com', 'www.baidu.com', 'l0', 'search',  '张三', 'win',  'master',    0),
  ('202601211000', 'subtask-02', 'search',     'test_search_empty',          'passed', 'www.sohu.com', 'www.sina.com', 'www.tencent.com', 'www.baidu.com', 'l1', 'search',  '张三', 'mac',  '930bugfix', 0),
  ('202601221500', 'subtask-03', 'profile,auth',   'test_update_avatar',         'passed', 'www.sohu.com', 'www.sina.com', 'www.tencent.com', 'www.baidu.com', 'l2', 'profile', '李四', 'ohos', 'master',    0),
  ('202601231200', 'subtask-04', 'profile,user','test_change_nickname',       'passed', 'www.sohu.com', 'www.sina.com', 'www.tencent.com', 'www.baidu.com', 'l3', 'profile', '李四', 'win',  '930bugfix', 0),
  ('202601241800', 'subtask-05', 'auth,user,order',        'test_login_success',         'passed', 'www.sohu.com', 'www.sina.com', 'www.tencent.com', 'www.baidu.com', 'l0', 'auth',    '张三', 'mac',  'master',    0),
  ('202601251000', 'subtask-06', 'auth',       'test_login_invalid_pwd',     'failed', 'www.sohu.com', 'www.sina.com', 'www.tencent.com', 'www.baidu.com', 'l1', 'auth',    '张三', 'ohos', '930bugfix', 0),
  ('202601261400', 'subtask-01', 'payment',     'test_pay_alipay',            'passed', 'www.sohu.com', 'www.sina.com', 'www.tencent.com', 'www.baidu.com', 'l2', 'payment', '李四', 'win',  'master',    0),
  ('202601271600', 'subtask-02', 'order,payment',        'test_create_order',          'passed', 'www.sohu.com', 'www.sina.com', 'www.tencent.com', 'www.baidu.com', 'l3', 'order',   '王五', 'mac',  '930bugfix', 0),
  ('202601281800', 'subtask-03', 'order,cart',      'test_cancel_order',          'passed', 'www.sohu.com', 'www.sina.com', 'www.tencent.com', 'www.baidu.com', 'l0', 'order',   '王五', 'ohos', 'master',    0),
  ('202601201730', 'subtask-04', 'cart,order',     'test_add_to_cart',           'failed', 'www.sohu.com', 'www.sina.com', 'www.tencent.com', 'www.baidu.com', 'l1', 'cart',    '赵六', 'win',  '930bugfix', 0),
  ('202601211000', 'subtask-05', 'search',        'test_search_keyword',        'passed', 'www.sohu.com', 'www.sina.com', 'www.tencent.com', 'www.baidu.com', 'l2', 'search',  '张三', 'mac',  'master',    0),
  ('202601221500', 'subtask-06', 'search',     'test_search_empty',          'passed', 'www.sohu.com', 'www.sina.com', 'www.tencent.com', 'www.baidu.com', 'l3', 'search',  '张三', 'ohos', '930bugfix', 0),
  ('202601231200', 'subtask-01', 'profile,auth',   'test_update_avatar',         'passed', 'www.sohu.com', 'www.sina.com', 'www.tencent.com', 'www.baidu.com', 'l0', 'profile', '李四', 'win',  'master',    0),
  ('202601241800', 'subtask-02', 'profile,user','test_change_nickname',       'failed', 'www.sohu.com', 'www.sina.com', 'www.tencent.com', 'www.baidu.com', 'l1', 'profile', '李四', 'mac',  '930bugfix', 0),
  ('202601251000', 'subtask-03', 'auth,user',        'test_login_success',         'passed', 'www.sohu.com', 'www.sina.com', 'www.tencent.com', 'www.baidu.com', 'l2', 'auth',    '张三', 'ohos', 'master',    0),
  ('202601261400', 'subtask-04', 'auth',       'test_login_invalid_pwd',     'passed', 'www.sohu.com', 'www.sina.com', 'www.tencent.com', 'www.baidu.com', 'l3', 'auth',    '张三', 'win',  '930bugfix', 0),
  ('202601271600', 'subtask-05', 'payment',     'test_pay_alipay',            'passed', 'www.sohu.com', 'www.sina.com', 'www.tencent.com', 'www.baidu.com', 'l0', 'payment', '李四', 'mac',  'master',    0),
  ('202601281800', 'subtask-06', 'order,payment',        'test_create_order',          'failed', 'www.sohu.com', 'www.sina.com', 'www.tencent.com', 'www.baidu.com', 'l1', 'order',   '王五', 'ohos', '930bugfix', 0),
  ('202601201730', 'subtask-01', 'order,cart,payment',      'test_cancel_order',          'passed', 'www.sohu.com', 'www.sina.com', 'www.tencent.com', 'www.baidu.com', 'l2', 'order',   '王五', 'win',  'master',    0),
  ('202601211000', 'subtask-02', 'cart,order',     'test_add_to_cart',           'passed', 'www.sohu.com', 'www.sina.com', 'www.tencent.com', 'www.baidu.com', 'l3', 'cart',    '赵六', 'mac',  '930bugfix', 0),
  ('202601221500', 'subtask-03', 'search',        'test_search_keyword',        'passed', 'www.sohu.com', 'www.sina.com', 'www.tencent.com', 'www.baidu.com', 'l0', 'search',  '张三', 'ohos', 'master',    0),
  ('202601231200', 'subtask-04', 'search',     'test_search_empty',          'failed', 'www.sohu.com', 'www.sina.com', 'www.tencent.com', 'www.baidu.com', 'l1', 'search',  '张三', 'win',  '930bugfix', 0),
  ('202601241800', 'subtask-05', 'profile,auth',   'test_update_avatar',         'passed', 'www.sohu.com', 'www.sina.com', 'www.tencent.com', 'www.baidu.com', 'l2', 'profile', '李四', 'mac',  'master',    0),
  ('202601251000', 'subtask-06', 'profile,user','test_change_nickname',       'passed', 'www.sohu.com', 'www.sina.com', 'www.tencent.com', 'www.baidu.com', 'l3', 'profile', '李四', 'ohos', '930bugfix', 0),
  ('202601261400', 'subtask-01', 'auth,user',        'test_login_success',         'passed', 'www.sohu.com', 'www.sina.com', 'www.tencent.com', 'www.baidu.com', 'l0', 'auth',    '张三', 'win',  'master',    0),
  ('202601271600', 'subtask-02', 'auth',       'test_login_invalid_pwd',     'passed', 'www.sohu.com', 'www.sina.com', 'www.tencent.com', 'www.baidu.com', 'l1', 'auth',    '张三', 'mac',  '930bugfix', 0),
  ('202601281800', 'subtask-03', 'payment',     'test_pay_alipay',            'passed', 'www.sohu.com', 'www.sina.com', 'www.tencent.com', 'www.baidu.com', 'l2', 'payment', '李四', 'ohos', 'master',    0),
  ('202601201730', 'subtask-04', 'order,payment',        'test_create_order',          'passed', 'www.sohu.com', 'www.sina.com', 'www.tencent.com', 'www.baidu.com', 'l3', 'order',   '王五', 'win',  '930bugfix', 0),
  ('202601211000', 'subtask-05', 'order,cart',      'test_cancel_order',          'failed', 'www.sohu.com', 'www.sina.com', 'www.tencent.com', 'www.baidu.com', 'l0', 'order',   '王五', 'mac',  'master',    0),
  ('202601221500', 'subtask-06', 'cart,order',     'test_add_to_cart',           'passed', 'www.sohu.com', 'www.sina.com', 'www.tencent.com', 'www.baidu.com', 'l1', 'cart',    '赵六', 'ohos', '930bugfix', 0),
  ('202601231200', 'subtask-01', 'search',        'test_search_keyword',        'passed', 'www.sohu.com', 'www.sina.com', 'www.tencent.com', 'www.baidu.com', 'l2', 'search',  '张三', 'win',  'master',    0),
  ('202601241800', 'subtask-02', 'search',     'test_search_empty',          'passed', 'www.sohu.com', 'www.sina.com', 'www.tencent.com', 'www.baidu.com', 'l3', 'search',  '张三', 'mac',  '930bugfix', 0),
  ('202601251000', 'subtask-03', 'profile,auth,user',   'test_update_avatar',         'failed', 'www.sohu.com', 'www.sina.com', 'www.tencent.com', 'www.baidu.com', 'l0', 'profile', '李四', 'ohos', 'master',    1),
  ('202601261400', 'subtask-04', 'profile,user','test_change_nickname',       'passed', 'www.sohu.com', 'www.sina.com', 'www.tencent.com', 'www.baidu.com', 'l1', 'profile', '李四', 'win',  '930bugfix', 0),
  ('202601271600', 'subtask-05', 'auth,user',        'test_login_success',         'passed', 'www.sohu.com', 'www.sina.com', 'www.tencent.com', 'www.baidu.com', 'l2', 'auth',    '张三', 'mac',  'master',    0),
  ('202601281800', 'subtask-06', 'auth',       'test_login_invalid_pwd',     'passed', 'www.sohu.com', 'www.sina.com', 'www.tencent.com', 'www.baidu.com', 'l3', 'auth',    '张三', 'ohos', '930bugfix', 0),
  ('202601201730', 'subtask-01', 'payment',     'test_pay_alipay',            'passed', 'www.sohu.com', 'www.sina.com', 'www.tencent.com', 'www.baidu.com', 'l0', 'payment', '李四', 'win',  'master',    0),
  ('202601211000', 'subtask-02', 'order,payment',        'test_create_order',          'passed', 'www.sohu.com', 'www.sina.com', 'www.tencent.com', 'www.baidu.com', 'l1', 'order',   '王五', 'mac',  '930bugfix', 0),
  ('202601221500', 'subtask-03', 'order,cart',      'test_cancel_order',          'passed', 'www.sohu.com', 'www.sina.com', 'www.tencent.com', 'www.baidu.com', 'l2', 'order',   '王五', 'ohos', 'master',    0),
  ('202601231200', 'subtask-04', 'cart,order,product',     'test_add_to_cart',           'passed', 'www.sohu.com', 'www.sina.com', 'www.tencent.com', 'www.baidu.com', 'l3', 'cart',    '赵六', 'win',  '930bugfix', 0),
  ('202601241800', 'subtask-05', 'search',        'test_search_keyword',        'failed', 'www.sohu.com', 'www.sina.com', 'www.tencent.com', 'www.baidu.com', 'l0', 'search',  '张三', 'mac',  'master',    0),
  ('202601251000', 'subtask-06', 'search',     'test_search_empty',          'passed', 'www.sohu.com', 'www.sina.com', 'www.tencent.com', 'www.baidu.com', 'l1', 'search',  '张三', 'ohos', '930bugfix', 0),
  ('202601261400', 'subtask-01', 'profile,auth',   'test_update_avatar',         'passed', 'www.sohu.com', 'www.sina.com', 'www.tencent.com', 'www.baidu.com', 'l2', 'profile', '李四', 'win',  'master',    0),
  ('202601271600', 'subtask-02', 'profile,user','test_change_nickname',       'passed', 'www.sohu.com', 'www.sina.com', 'www.tencent.com', 'www.baidu.com', 'l3', 'profile', '李四', 'mac',  '930bugfix', 0),
  ('202601281800', 'subtask-03', 'auth,user',        'test_login_success',         'passed', 'www.sohu.com', 'www.sina.com', 'www.tencent.com', 'www.baidu.com', 'l0', 'auth',    '张三', 'ohos', 'master',    0),
  ('202601201730', 'subtask-04', 'auth',       'test_login_invalid_pwd',     'failed', 'www.sohu.com', 'www.sina.com', 'www.tencent.com', 'www.baidu.com', 'l1', 'auth',    '张三', 'win',  '930bugfix', 0),
  ('202601211000', 'subtask-05', 'payment',     'test_pay_alipay',            'passed', 'www.sohu.com', 'www.sina.com', 'www.tencent.com', 'www.baidu.com', 'l2', 'payment', '李四', 'mac',  'master',    0),
  ('202601221500', 'subtask-06', 'order,payment',        'test_create_order',          'passed', 'www.sohu.com', 'www.sina.com', 'www.tencent.com', 'www.baidu.com', 'l3', 'order',   '王五', 'ohos', '930bugfix', 0),
  ('202601231200', 'subtask-01', 'order,cart',      'test_cancel_order',          'passed', 'www.sohu.com', 'www.sina.com', 'www.tencent.com', 'www.baidu.com', 'l0', 'order',   '王五', 'win',  'master',    0),
  ('202601241800', 'subtask-02', 'cart,order',     'test_add_to_cart',           'passed', 'www.sohu.com', 'www.sina.com', 'www.tencent.com', 'www.baidu.com', 'l1', 'cart',    '赵六', 'mac',  '930bugfix', 0),
  ('202601251000', 'subtask-03', 'search',        'test_search_keyword',        'passed', 'www.sohu.com', 'www.sina.com', 'www.tencent.com', 'www.baidu.com', 'l2', 'search',  '张三', 'ohos', 'master',    0),
  ('202601261400', 'subtask-04', 'search',     'test_search_empty',          'passed', 'www.sohu.com', 'www.sina.com', 'www.tencent.com', 'www.baidu.com', 'l3', 'search',  '张三', 'win',  '930bugfix', 0),
  ('202601271600', 'subtask-05', 'profile,auth',   'test_update_avatar',         'passed', 'www.sohu.com', 'www.sina.com', 'www.tencent.com', 'www.baidu.com', 'l0', 'profile', '李四', 'mac',  'master',    0),
  ('202601281800', 'subtask-06', 'profile,user,auth','test_change_nickname',       'failed', 'www.sohu.com', 'www.sina.com', 'www.tencent.com', 'www.baidu.com', 'l1', 'profile', '李四', 'ohos', '930bugfix', 0),
  ('202601201730', 'subtask-01', 'auth,user',        'test_login_success',         'passed', 'www.sohu.com', 'www.sina.com', 'www.tencent.com', 'www.baidu.com', 'l2', 'auth',    '张三', 'win',  'master',    0),
  ('202601211000', 'subtask-02', 'auth',       'test_login_invalid_pwd',     'passed', 'www.sohu.com', 'www.sina.com', 'www.tencent.com', 'www.baidu.com', 'l3', 'auth',    '张三', 'mac',  '930bugfix', 0),
  ('202601221500', 'subtask-03', 'payment',     'test_pay_alipay',            'passed', 'www.sohu.com', 'www.sina.com', 'www.tencent.com', 'www.baidu.com', 'l0', 'payment', '李四', 'ohos', 'master',    0),
  ('202601231200', 'subtask-04', 'order,payment',        'test_create_order',          'failed', 'www.sohu.com', 'www.sina.com', 'www.tencent.com', 'www.baidu.com', 'l1', 'order',   '王五', 'win',  '930bugfix', 0),
  ('202601241800', 'subtask-05', 'order,cart',      'test_cancel_order',          'passed', 'www.sohu.com', 'www.sina.com', 'www.tencent.com', 'www.baidu.com', 'l2', 'order',   '王五', 'mac',  'master',    0),
  ('202601251000', 'subtask-06', 'cart,order',     'test_add_to_cart',           'passed', 'www.sohu.com', 'www.sina.com', 'www.tencent.com', 'www.baidu.com', 'l3', 'cart',    '赵六', 'ohos', '930bugfix', 0),
  ('202601261400', 'subtask-01', 'search',        'test_search_keyword',        'passed', 'www.sohu.com', 'www.sina.com', 'www.tencent.com', 'www.baidu.com', 'l0', 'search',  '张三', 'win',  'master',    0),
  ('202601271600', 'subtask-02', 'search',     'test_search_empty',          'passed', 'www.sohu.com', 'www.sina.com', 'www.tencent.com', 'www.baidu.com', 'l1', 'search',  '张三', 'mac',  '930bugfix', 0),
  ('202601281800', 'subtask-03', 'profile,auth',   'test_update_avatar',         'passed', 'www.sohu.com', 'www.sina.com', 'www.tencent.com', 'www.baidu.com', 'l2', 'profile', '李四', 'ohos', 'master',    0),
  ('202601201730', 'subtask-04', 'profile,user','test_change_nickname',       'passed', 'www.sohu.com', 'www.sina.com', 'www.tencent.com', 'www.baidu.com', 'l3', 'profile', '李四', 'win',  '930bugfix', 0),
  ('202601211000', 'subtask-05', 'auth,user',        'test_login_success',         'passed', 'www.sohu.com', 'www.sina.com', 'www.tencent.com', 'www.baidu.com', 'l0', 'auth',    '张三', 'mac',  'master',    0),
  ('202601221500', 'subtask-06', 'auth',       'test_login_invalid_pwd',     'passed', 'www.sohu.com', 'www.sina.com', 'www.tencent.com', 'www.baidu.com', 'l1', 'auth',    '张三', 'ohos', '930bugfix', 0),
  ('202601231200', 'subtask-01', 'payment',     'test_pay_alipay',            'failed', 'www.sohu.com', 'www.sina.com', 'www.tencent.com', 'www.baidu.com', 'l2', 'payment', '李四', 'win',  'master',    0),
  ('202601241800', 'subtask-02', 'order,payment,cart',        'test_create_order',          'passed', 'www.sohu.com', 'www.sina.com', 'www.tencent.com', 'www.baidu.com', 'l3', 'order',   '王五', 'mac',  '930bugfix', 0),
  ('202601251000', 'subtask-03', 'order,cart',      'test_cancel_order',          'passed', 'www.sohu.com', 'www.sina.com', 'www.tencent.com', 'www.baidu.com', 'l0', 'order',   '王五', 'ohos', 'master',    0),
  ('202601261400', 'subtask-04', 'cart,order',     'test_add_to_cart',           'passed', 'www.sohu.com', 'www.sina.com', 'www.tencent.com', 'www.baidu.com', 'l1', 'cart',    '赵六', 'win',  '930bugfix', 0),
  ('202601271600', 'subtask-05', 'search',        'test_search_keyword',        'passed', 'www.sohu.com', 'www.sina.com', 'www.tencent.com', 'www.baidu.com', 'l2', 'search',  '张三', 'mac',  'master',    0),
  ('202601281800', 'subtask-06', 'search',     'test_search_empty',          'passed', 'www.sohu.com', 'www.sina.com', 'www.tencent.com', 'www.baidu.com', 'l3', 'search',  '张三', 'ohos', '930bugfix', 0),
  ('202601201730', 'subtask-01', 'profile,auth',   'test_update_avatar',         'passed', 'www.sohu.com', 'www.sina.com', 'www.tencent.com', 'www.baidu.com', 'l0', 'profile', '李四', 'win',  'master',    0),
  ('202601211000', 'subtask-02', 'profile,user','test_change_nickname',       'passed', 'www.sohu.com', 'www.sina.com', 'www.tencent.com', 'www.baidu.com', 'l1', 'profile', '李四', 'mac',  '930bugfix', 0);
